// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file chat.proto (package chat, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChatMessage, StreamMessage, SubscribeRequest } from "./chat_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * Service definition
 *
 * @generated from service chat.ChatService
 */
export const ChatService = {
  typeName: "chat.ChatService",
  methods: {
    /**
     * Unary call for sending messages (Client -> Server)
     *
     * @generated from rpc chat.ChatService.SendMessage
     */
    sendMessage: {
      name: "SendMessage",
      I: ChatMessage,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Server streaming for receiving messages (Server -> Client)
     *
     * @generated from rpc chat.ChatService.SubscribeMessages
     */
    subscribeMessages: {
      name: "SubscribeMessages",
      I: SubscribeRequest,
      O: StreamMessage,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

